import type { Metadata } from "next";
import "@/shared/assets/css/global.css";
import React from "react";
import { authOptions } from "@/shared/lib/next-auth/options";
import { AuthProvider } from "@/app/providers/AuthProvider";
import { getServerSession } from "next-auth";
import { cn } from "@/lib/utils";
import { euclidCircular } from "@/shared/assets/fonts";

export const metadata: Metadata = {
  title: "Project Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Project management</title>
      </head>
      <body className={cn("antialiased", euclidCircular.className)}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
